"use client";
import { useState } from "react";
import { Card, Badge, Button } from "@naples/ui";
import { Sparkles, Building2, Mic2, Award, ChevronRight, Copy, Check, Download } from "lucide-react";
import clsx from "clsx";

interface Pkg {
  tier: "Bronze" | "Silver" | "Gold";
  price_per_show: number;
  inclusions: string[];
}
interface Pitch {
  audience_match: string;
  packages: Pkg[];
  integration_ideas: string[];
  source: "api" | "mock" | "fallback";
  id: string | null;
}
interface RecentPitch {
  id: string;
  sponsor_name: string;
  show: string;
  created_at: string;
}

const SHOWS = ["Billionaire Coast", "239 Built", "SWFL Keys"];

export function Builder({ recentPitches }: { recentPitches: RecentPitch[] }) {
  const [sponsor, setSponsor] = useState("");
  const [show, setShow] = useState(SHOWS[0]);
  const [pitch, setPitch] = useState<Pitch | null>(null);
  const [generating, setGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  async function generate() {
    if (!sponsor.trim()) return;
    setGenerating(true);
    setPitch(null);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sponsorName: sponsor.trim(), show }),
      });
      const json = (await res.json()) as Pitch;
      setPitch(json);
    } catch {
      // ignore
    } finally {
      setGenerating(false);
    }
  }

  function copyAll() {
    if (!pitch) return;
    const text = formatPlainText(pitch, sponsor, show);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="px-6 py-12">
      <header className="mx-auto max-w-7xl">
        <div className="text-[10px] uppercase tracking-[0.32em] text-gold">Sales Engine</div>
        <h1 className="mt-3 font-heading text-5xl text-cream">Sponsor Pitch Builder</h1>
        <div className="mt-3 h-px w-16 bg-gold" />
        <p className="mt-4 max-w-2xl text-sm text-cream/70">
          Type a sponsor company. Pick the show. Get a custom one-pager with audience match,
          tiered packages, and 5 integration ideas — generated by Claude in under 30 seconds.
          Send it the same day.
        </p>
      </header>

      <div className="mx-auto mt-8 grid max-w-7xl grid-cols-1 gap-6 lg:grid-cols-12">
        <div className="lg:col-span-8 space-y-6">
          <Card>
            <div className="grid gap-4 md:grid-cols-2">
              <div>
                <label className="text-[10px] uppercase tracking-wider text-muted">Sponsor Company *</label>
                <div className="mt-1.5 flex items-center gap-2 border border-card-border bg-bg px-3 py-2.5">
                  <Building2 className="h-4 w-4 text-muted" />
                  <input
                    value={sponsor}
                    onChange={(e) => setSponsor(e.target.value)}
                    placeholder="e.g., Naples Yacht Club"
                    className="w-full bg-transparent text-sm text-cream placeholder:text-muted/60 focus:outline-none"
                  />
                </div>
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-muted">Show</label>
                <div className="mt-1.5 flex items-center gap-2 border border-card-border bg-bg px-3 py-2.5">
                  <Mic2 className="h-4 w-4 text-muted" />
                  <select
                    value={show}
                    onChange={(e) => setShow(e.target.value)}
                    className="w-full bg-transparent text-sm text-cream focus:outline-none"
                  >
                    {SHOWS.map((s) => <option key={s}>{s}</option>)}
                  </select>
                </div>
              </div>
            </div>
            <div className="mt-6 flex justify-end">
              <Button onClick={generate} disabled={!sponsor.trim() || generating}>
                {generating ? (<><Sparkles className="mr-2 h-4 w-4 animate-pulse" /> Generating…</>) : (<><Sparkles className="mr-2 h-4 w-4" /> Generate Pitch</>)}
              </Button>
            </div>
          </Card>

          {generating && <Loading />}

          {pitch && (
            <PitchOnePager pitch={pitch} sponsor={sponsor} show={show} onCopy={copyAll} copied={copied} />
          )}
        </div>

        <aside className="lg:col-span-4">
          <Card>
            <div className="text-[10px] uppercase tracking-[0.18em] text-muted">Recent Pitches</div>
            <h2 className="mt-1 font-heading text-xl text-cream">Last {recentPitches.length}</h2>
            {recentPitches.length === 0 ? (
              <p className="mt-3 text-sm text-muted">
                No pitches yet. The first one Kevin generates will show up here.
              </p>
            ) : (
              <div className="mt-4 divide-y divide-card-border text-sm">
                {recentPitches.map((p) => (
                  <div key={p.id} className="py-2.5">
                    <div className="text-cream">{p.sponsor_name}</div>
                    <div className="text-[11px] text-muted">{p.show} · {timeAgo(p.created_at)}</div>
                  </div>
                ))}
              </div>
            )}
          </Card>
        </aside>
      </div>
    </div>
  );
}

function PitchOnePager({ pitch, sponsor, show, onCopy, copied }: {
  pitch: Pitch; sponsor: string; show: string; onCopy: () => void; copied: boolean;
}) {
  const sourceLabel = pitch.source === "api" ? "Live · Claude Sonnet 4.6"
    : pitch.source === "fallback" ? "Preview mode (API fallback)"
    : "Preview mode";
  const sourceCls = pitch.source === "api" ? "border-gold/60 text-gold"
    : pitch.source === "fallback" ? "border-amber/60 text-amber"
    : "border-card-border text-muted";

  return (
    <Card>
      <div className="flex items-center justify-between">
        <span className={`border px-2.5 py-1 text-[10px] uppercase tracking-wider ${sourceCls}`}>
          {sourceLabel}
        </span>
        <Button variant="ghost" size="sm" onClick={onCopy}>
          {copied ? (<><Check className="mr-2 h-3.5 w-3.5 text-emerald" /> Copied</>) : (<><Copy className="mr-2 h-3.5 w-3.5" /> Copy One-Pager</>)}
        </Button>
      </div>

      <div className="mt-6 border-l-2 border-gold pl-4">
        <div className="text-[10px] uppercase tracking-[0.18em] text-muted">Sponsorship One-Pager</div>
        <h2 className="mt-1 font-heading text-3xl text-cream">{sponsor} × {show}</h2>
      </div>

      <section className="mt-8">
        <div className="text-[10px] uppercase tracking-[0.18em] text-gold">Audience Match</div>
        <p className="mt-2 text-sm leading-relaxed text-cream/90">{pitch.audience_match}</p>
      </section>

      <section className="mt-8">
        <div className="text-[10px] uppercase tracking-[0.18em] text-gold">Package Tiers</div>
        <div className="mt-3 grid gap-3 md:grid-cols-3">
          {pitch.packages.map((p) => <PackageCard key={p.tier} pkg={p} />)}
        </div>
      </section>

      <section className="mt-8">
        <div className="text-[10px] uppercase tracking-[0.18em] text-gold">Integration Ideas</div>
        <ul className="mt-3 space-y-2.5">
          {pitch.integration_ideas.map((idea, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-cream/90">
              <ChevronRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-gold" />
              <span>{idea}</span>
            </li>
          ))}
        </ul>
      </section>

      <div className="mt-10 border-t border-card-border pt-6 text-[11px] text-muted">
        Prepared by Naples Digital × 239 Live Studios. Pitch persisted to <code className="text-gold/80">sponsor_pitches</code>.
        Send when ready.
      </div>
    </Card>
  );
}

function PackageCard({ pkg }: { pkg: Pkg }) {
  const tierColor = pkg.tier === "Gold" ? "border-gold bg-gold/5"
    : pkg.tier === "Silver" ? "border-cream/40 bg-cream/5"
    : "border-amber/60 bg-amber/5";
  return (
    <div className={clsx("border p-4", tierColor)}>
      <div className="flex items-center gap-2">
        <Award className={clsx("h-4 w-4", pkg.tier === "Gold" ? "text-gold" : pkg.tier === "Silver" ? "text-cream" : "text-amber")} />
        <span className="text-[11px] uppercase tracking-wider text-cream">{pkg.tier}</span>
      </div>
      <div className="mt-2 font-heading text-2xl text-cream">${pkg.price_per_show}<span className="text-sm text-muted">/show</span></div>
      <ul className="mt-4 space-y-1.5 text-xs text-cream/80">
        {pkg.inclusions.map((inc, i) => (
          <li key={i} className="flex items-start gap-1.5">
            <span className="mt-1 h-1 w-1 shrink-0 rounded-full bg-gold" />
            <span>{inc}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function Loading() {
  return (
    <Card>
      <div className="flex flex-col items-center gap-3 py-10">
        <Sparkles className="h-7 w-7 animate-pulse text-gold" />
        <div className="text-sm text-muted">Building the one-pager…</div>
      </div>
    </Card>
  );
}

function timeAgo(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  const m = Math.floor(ms / 60000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

function formatPlainText(p: Pitch, sponsor: string, show: string): string {
  const lines: string[] = [];
  lines.push(`${sponsor} × ${show} — Sponsorship One-Pager\n`);
  lines.push(`AUDIENCE MATCH\n${p.audience_match}\n`);
  lines.push(`PACKAGES`);
  for (const pkg of p.packages) {
    lines.push(`  ${pkg.tier} — $${pkg.price_per_show}/show`);
    for (const inc of pkg.inclusions) lines.push(`    • ${inc}`);
  }
  lines.push(`\nINTEGRATION IDEAS`);
  for (const idea of p.integration_ideas) lines.push(`  • ${idea}`);
  lines.push(`\n— Naples Digital × 239 Live Studios`);
  return lines.join("\n");
}
