-- 0011_makerschool_full_extraction.sql
-- Capture the missing fields from Gemini extraction:
--  - summary           (2-3 sentence neutral summary)
--  - workflow_configs  (configs/scenarios shown on screen)
--  - transcript        (verbatim transcript, generated by Gemini's video understanding)
--  - chunk_count       (>1 for videos chunked due to >1hr Gemini cap)

alter table public.makerschool_videos
  add column if not exists summary           text,
  add column if not exists workflow_configs  text[] default '{}',
  add column if not exists transcript        text,
  add column if not exists chunk_count       integer default 1;

create index if not exists makerschool_videos_transcript_fts_idx
  on public.makerschool_videos
  using gin (to_tsvector('english', coalesce(transcript, '')));

create index if not exists makerschool_action_items_desc_fts_idx
  on public.makerschool_action_items
  using gin (to_tsvector('english', description));
