// Resend email helper. Falls back to console.log if RESEND_API_KEY not set.
//
// "From" address comes from tenant_integrations.config.from_address (per-tenant).
// "To" addresses come from tenant_integrations.config.alert_recipients[].
// API key is platform-level (Doppler RESEND_API_KEY) — Naples Digital owns the
// Resend account and bills clients via the platform fee, not pass-through.

import { listAlertRecipients } from "@naples/db";
import { createServerClient } from "@naples/db";

export type DealAlertPayload = {
  tenantId: string;
  dealUrl: string;
  title: string;
  underwritingSummary: string;
  unitCount: number | null;
  askingPrice: number | null;
  city: string | null;
  state: string | null;
};

export async function sendDealAlert(payload: DealAlertPayload): Promise<{ ok: boolean; via: "resend" | "console" | "skipped"; reason?: string }> {
  const recipients = await listAlertRecipients(payload.tenantId);
  if (recipients.length === 0) {
    console.log(`[email] no recipients for tenant ${payload.tenantId} — skipping alert for "${payload.title}"`);
    return { ok: true, via: "skipped", reason: "no recipients configured" };
  }

  const fromConfig = await getResendConfig(payload.tenantId);
  const subject = `[MIA Deal Alert] ${payload.title}` +
    (payload.unitCount ? ` · ${payload.unitCount} units` : "") +
    (payload.askingPrice ? ` · $${(payload.askingPrice / 1_000_000).toFixed(1)}M` : "");
  const html = renderAlertHtml(payload);

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.log(`[email] RESEND_API_KEY not set — would send to ${recipients.join(", ")}: ${subject}`);
    return { ok: true, via: "console", reason: "RESEND_API_KEY not set" };
  }

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: `${fromConfig.fromName} <${fromConfig.fromAddress}>`,
        to: recipients,
        subject,
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.text();
      console.error(`[email] resend failed ${res.status}: ${body}`);
      return { ok: false, via: "resend", reason: `${res.status}: ${body.slice(0, 200)}` };
    }
    console.log(`[email] sent "${subject}" to ${recipients.length} recipient(s)`);
    return { ok: true, via: "resend" };
  } catch (e) {
    console.error("[email] resend exception", e);
    return { ok: false, via: "resend", reason: e instanceof Error ? e.message : "unknown" };
  }
}

async function getResendConfig(tenantId: string): Promise<{ fromAddress: string; fromName: string }> {
  const sb = createServerClient();
  const { data } = await sb.from("tenant_integrations")
    .select("config").eq("tenant_id", tenantId).eq("kind", "resend").maybeSingle();
  const config = (data as { config?: Record<string, unknown> } | null)?.config ?? {};
  return {
    fromAddress: (config.from_address as string) ?? "deals@naplesdigital.app",
    fromName: (config.from_name as string) ?? "Naples Digital Deal Bot",
  };
}

function renderAlertHtml(p: DealAlertPayload): string {
  const summary = p.underwritingSummary
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/\n/g, "<br>");
  const location = [p.city, p.state].filter(Boolean).join(", ");
  return `<!doctype html>
<html><body style="margin:0;padding:24px;background:#0A0A0A;font-family:Inter,system-ui,sans-serif;color:#F5F5F5">
<div style="max-width:600px;margin:0 auto">
  <div style="font-size:11px;letter-spacing:0.32em;text-transform:uppercase;color:#8A6BB8;margin-bottom:8px">MIA Deal Alert</div>
  <h1 style="font-family:'Bebas Neue',Impact,sans-serif;font-size:36px;letter-spacing:0.04em;margin:0 0 4px;color:#F5F5F5">${escape(p.title)}</h1>
  ${location ? `<div style="font-size:13px;color:#A0A0A0;margin-bottom:16px">${escape(location)}</div>` : ""}
  <div style="border-left:3px solid #8A6BB8;padding:12px 16px;margin:16px 0;background:#111;border-top:1px solid #1A1A1A;border-right:1px solid #1A1A1A;border-bottom:1px solid #1A1A1A;font-size:13px;line-height:1.6;color:#E0E0E0">${summary}</div>
  <p style="margin:24px 0 8px"><a href="${p.dealUrl}" style="display:inline-block;padding:10px 18px;background:#8A6BB8;color:#0A0A0A;text-decoration:none;font-size:11px;letter-spacing:0.1em;text-transform:uppercase;font-weight:600">Open in MIA Tools</a></p>
  <p style="font-size:11px;color:#666;margin-top:32px">Auto-generated by Naples Digital · Reply to this email for human follow-up.</p>
</div>
</body></html>`;
}

function escape(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
